apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fulcio-createcerts
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fulcio-createcerts
    app.kubernetes.io/part-of: scaffold
  name: fulcio-createcerts
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: fulcio-createcerts
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: fulcio-createcerts
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold/fulcio-createcerts@sha256:0c0bc19407291b9eb0129a8eb46f4510302cdb47d69628a819f5f4ab676525fe
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
