apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ctlog-verify-fulcio
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ctlog-verify-fulcio
    app.kubernetes.io/part-of: scaffold
  name: ctlog-verify-fulcio
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: ctlog-verify-fulcio
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: ctlog-verify-fulcio
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold/ctlog-verify-fulcio@sha256:479270f85c5c53eaf894b690578d255751eb01e0cc329c77a2279baa2571f86a
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
