apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: trillian-createdb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: trillian-createdb
    app.kubernetes.io/part-of: scaffold
  name: trillian-createdb
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: trillian-createdb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: trillian-createdb
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold/trillian-createdb@sha256:35986114b85a4fa21250526c8923a5cd56f6bd16fe399e1103d56d4810eac8ce
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
