apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: trillian-createdb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: trillian-createdb
    app.kubernetes.io/part-of: scaffold
  name: trillian-createdb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: trillian-createdb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: trillian-createdb
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold/trillian-createdb@sha256:8f23ee6b3e41adf245d02e03baddfa2f70039e3327d80ae677245149091ceaa1
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
