apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: tuf-server
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold/tuf-server@sha256:0a69ddd39ab0e76fe23e5a32c3643c8c725b6f38411eab9b657ffccaf96c6b3d
        name: my-go
        resources: {}
status: {}
