apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: tuf-server
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold/tuf-server@sha256:d494df01d273b42b8c829f16d2f1556080c82f4b5d18e13e77c2caa00dfea9e1
        name: my-go
        resources: {}
status: {}
