apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tuf-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tuf-server
    app.kubernetes.io/part-of: scaffold
  name: tuf-serveracdz
spec:
  path: /
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: tuf-server
    weight: null
status: {}
