apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trillian-createdb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold/trillian-createdb@sha256:f5c22f733d7f37974a573906df1635def0a8d23bee37bc0aac49466817f1725e
        name: my-go
        resources: {}
status: {}
