apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trillian-createdb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold/trillian-createdb@sha256:2fc6e590399e316d0f63a556162c1f7bde5f13864116ae05f5189f1d6ff03e6f
        name: my-go
        resources: {}
status: {}
