apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trillian-createdb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold/trillian-createdb@sha256:fa85277212c2d16e6596fd4e6453c08d2266e527d1dc8592c67fb8586da602ca
        name: my-go
        resources: {}
status: {}
