apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ct-server
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold/ct-server@sha256:b3f066ae8b941aaa55d30f29c2306e532260855d12a14f308f4c09c96de942ce
        name: my-go
        resources: {}
status: {}
