apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ct-server
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold/ct-server@sha256:0419d1e98125cb9fb5d67807659455684e34829499df859185fcb808b865a618
        name: my-go
        resources: {}
status: {}
