apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ctlog-verify-fulcio
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold/ctlog-verify-fulcio@sha256:81a7dac318507537892de4bf86c72fd90638096b4e17bb5b5099f4ff67e610e3
        name: my-go
        resources: {}
status: {}
