apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ctlog-managectroots
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold/ctlog-managectroots@sha256:5d1291d3f618294dc95438c9f62aa94e9325bc49e65e4568a2340a2f233462d4
        name: my-go
        resources: {}
status: {}
