apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: createctconfig
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: createctconfig
    app.kubernetes.io/part-of: scaffold
  name: createctconfig
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: createctconfig
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: createctconfig
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold/createctconfig@sha256:e89f4a8d9946b66fad8f878c724a56182ee0e0f739357131aa5288e2bd4cc4ef
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
